/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controladores.Manejador;
import controladores.Navegadores;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author mariela
 */


public class VentanaPrincipal extends javax.swing.JFrame {
    
     Manejador manejador = new Manejador();
    private static final String ruta = "c:\\tmp\\";
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.colocarFondo();
        this.setLocationRelativeTo(null);
        this.setTitle("Detector de Incompatibilidades WEB");
    }
    
    public void colocarFondo(){
        PanelPrincipal panel = new PanelPrincipal();
        this.add(panel,BorderLayout.CENTER);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelURL = new javax.swing.JPanel();
        urlTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        panelBotonera = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botonComparar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        checkChrome = new javax.swing.JCheckBox();
        checkFireFox = new javax.swing.JCheckBox();
        checkIE = new javax.swing.JCheckBox();
        checkOpera = new javax.swing.JCheckBox();
        panelTitulo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        panelURL.setOpaque(false);

        urlTextField.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        urlTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese la URL:");

        labelNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setText("Ingrese nombre de la prueba:");

        nombreTextField.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelURLLayout = new javax.swing.GroupLayout(panelURL);
        panelURL.setLayout(panelURLLayout);
        panelURLLayout.setHorizontalGroup(
            panelURLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelURLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelURLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelURLLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(urlTextField))
                    .addGroup(panelURLLayout.createSequentialGroup()
                        .addComponent(labelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        panelURLLayout.setVerticalGroup(
            panelURLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelURLLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelURLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(panelURLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33))
        );

        panelBotonera.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione los navegadores a comprar:");

        botonComparar.setText("Comparar");
        botonComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCompararActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        checkChrome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        checkChrome.setForeground(new java.awt.Color(255, 255, 255));
        checkChrome.setText("Chrome");
        checkChrome.setOpaque(false);

        checkFireFox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        checkFireFox.setForeground(new java.awt.Color(255, 255, 255));
        checkFireFox.setText("Mozilla Firefox");
        checkFireFox.setOpaque(false);

        checkIE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        checkIE.setForeground(new java.awt.Color(255, 255, 255));
        checkIE.setText("Internet Explorer");
        checkIE.setOpaque(false);

        checkOpera.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        checkOpera.setForeground(new java.awt.Color(255, 255, 255));
        checkOpera.setText("Opera");
        checkOpera.setOpaque(false);

        javax.swing.GroupLayout panelBotoneraLayout = new javax.swing.GroupLayout(panelBotonera);
        panelBotonera.setLayout(panelBotoneraLayout);
        panelBotoneraLayout.setHorizontalGroup(
            panelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoneraLayout.createSequentialGroup()
                .addGroup(panelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotoneraLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(panelBotoneraLayout.createSequentialGroup()
                                .addComponent(checkChrome)
                                .addGap(85, 85, 85)
                                .addComponent(checkFireFox)
                                .addGap(66, 66, 66)
                                .addComponent(checkIE)
                                .addGap(75, 75, 75)
                                .addComponent(checkOpera))))
                    .addGroup(panelBotoneraLayout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(botonComparar)
                        .addGap(83, 83, 83)
                        .addComponent(botonCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBotoneraLayout.setVerticalGroup(
            panelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoneraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(62, 62, 62)
                .addGroup(panelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkChrome)
                    .addComponent(checkFireFox)
                    .addComponent(checkIE)
                    .addComponent(checkOpera))
                .addGap(57, 57, 57)
                .addGroup(panelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonComparar)
                    .addComponent(botonCancelar))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        panelTitulo.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Detector de Incompatibilidades WEB ");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel4)
                .addGap(60, 60, 60)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBotonera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelURL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(panelBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urlTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlTextFieldActionPerformed

    private void botonCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCompararActionPerformed
        
       
        //codigo para obtener la URL
        String url = this.urlTextField.getText();
                
        if(url.isEmpty()){
            JOptionPane.showMessageDialog(this,
                    "Debe ingresar una URL válida.",
                    "Atención",
                    JOptionPane.ERROR_MESSAGE);
        
        } else if (url.length() < 10) {
            JOptionPane.showMessageDialog(this,
                    "La URL no es válida.",
                    "Atención",
                    JOptionPane.ERROR_MESSAGE);
        
        } else if(  ((url.substring(0,7)).equals("http://")) ||
                    ((url.substring(0,8)).equals("https://")) )
                {
             
                                    
                    
            String navegador1 =  "";
            String navegador2 = "";
        
            if(validarCantidadNavegadores() != null){
                
                    int respuesta = JOptionPane.showConfirmDialog(null,
                       "Una vez iniciado el proceso de comparación, la aplicación no se"
                               + " detendrá hasta completarlo. Desea continuar?", "Atención",
                     JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                       if (respuesta == JOptionPane.YES_OPTION){
                
                
                
                navegador1 = validarCantidadNavegadores().get(0);
                navegador2 = validarCantidadNavegadores().get(1);
                
                String nombrePrueba = this.nombreTextField.getText();
                
                
                manejador.compararImg(navegador1, navegador2, url, ruta, nombrePrueba);
            }
            }
        } else {
            
            JOptionPane.showMessageDialog(this,
                    "La URL debe contener el prefijo \"http://\" o \"https://\".",
                    "Atención",
                    JOptionPane.ERROR_MESSAGE);  
            
        
        }
        
        
        
        
    }//GEN-LAST:event_botonCompararActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        manejador.finalizarProceso();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFieldActionPerformed

  
    private ArrayList<String> validarCantidadNavegadores(){
        ArrayList<String> seleccionados = new ArrayList<String>();
        
        if(checkChrome.isSelected()){
            seleccionados.add(Navegadores.CHROME);
        }        
        if(checkFireFox.isSelected()){
            seleccionados.add(Navegadores.FF);
        }        
        if(checkIE.isSelected()){
            seleccionados.add(Navegadores.IE);
        }        
        if(checkOpera.isSelected()){
            seleccionados.add(Navegadores.OPERA);
        }        
        if (seleccionados.isEmpty() || seleccionados.size() == 1) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar al menos dos opciones.",
                    "Atención",
                    JOptionPane.ERROR_MESSAGE);
            return null;
        
        } else if (seleccionados.size() > 2) {
            JOptionPane.showMessageDialog(this,
                    "No puenden estar seleccionados más de dos navegadores.",
                    "Atención",
                    JOptionPane.ERROR_MESSAGE);
            return null;
        }
        
        return seleccionados;
        
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonComparar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkChrome;
    private javax.swing.JCheckBox checkFireFox;
    private javax.swing.JCheckBox checkIE;
    private javax.swing.JCheckBox checkOpera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JPanel panelBotonera;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelURL;
    private javax.swing.JTextField urlTextField;
    // End of variables declaration//GEN-END:variables
}
